INTER.CORE/Inter.Core.Presentation/Controllers/FileUploadController.cs
using Inter.Core.App.Intefaces;
using Inter.Core.App.ViewModel;
using Inter.Core.Presentation.Configuration;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.IO;
using System.Threading.Tasks;

namespace Inter.Core.Presentation.Controllers
{
    //[Authorize(Roles = "Admin, Users")]
    public class FileUploadController : Controller
    {
        private readonly IOptions<AppSettings> _appSetttings;
        private readonly IFileUploadAppService _fileUploadAppService;
        private readonly ICulturalExchangeFileUploadAppService _culturalExchangeFileUploadAppService;
        private readonly ICulturalExchangeAppService _culturalExchangeAppService;

        public FileUploadController(
            IOptions<AppSettings> appSetttings,
            ICulturalExchangeFileUploadAppService culturalExchangeFileUploadAppService,
            IFileUploadAppService fileUploadAppService,
            ICulturalExchangeAppService culturalExchangeAppService)
        {
            _appSetttings = appSetttings;
            _fileUploadAppService = fileUploadAppService;
            _culturalExchangeFileUploadAppService = culturalExchangeFileUploadAppService;
            _culturalExchangeAppService = culturalExchangeAppService;

        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Download(string fileName, Guid culturalExchangeId)
        {
            if (string.IsNullOrWhiteSpace(fileName))
                return Content("filename not present");

            var culturalExchange = _culturalExchangeAppService.GetById(culturalExchangeId);

            if (culturalExchange == null)
                return Content("Cultural Exchange not found");

            var path = Path.Combine(_appSetttings.Value.UploadFilePath + culturalExchange.Id, fileName);

            var stream = new FileStream(path, FileMode.Open);

            return File(stream, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public async Task<IActionResult> CulturalExchangeDeleteFile(Guid id, string fileName, Guid culturalExchangeId)
        {
            try
            {
                if (id != Guid.Empty && !string.IsNullOrWhiteSpace(fileName))
                {
                    _culturalExchangeFileUploadAppService.Delete(id);
                    
                    _fileUploadAppService.Delete(_appSetttings.Value.UploadFilePath + culturalExchangeId, fileName);

                    return Json(Ok());
                }

                return Json(Conflict());
            }
            catch (Exception ex)
            {
                return Json(BadRequest());
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetModalCulturalExchangeUploadFile(Guid culturalExchangeId)
        {
            CulturalExchangeFileUploadViewModel culturalExchangeFileUploadViewModel = new CulturalExchangeFileUploadViewModel();
            culturalExchangeFileUploadViewModel.CulturalExchangeId = culturalExchangeId;

            return PartialView("~/Views/FileUpload/_partial/_modal_culturalExchange_upload_file.cshtml", culturalExchangeFileUploadViewModel);
        }

        [HttpPost]
        public async Task<JsonResult> PostModalCulturalExchangeUploadFile(CulturalExchangeFileUploadViewModel fileUploadViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var culturalExchange = _culturalExchangeAppService.GetById(fileUploadViewModel.CulturalExchangeId);

                    fileUploadViewModel.FileName = await _fileUploadAppService.Upload(_appSetttings.Value.UploadFilePath + culturalExchange.Id, null, fileUploadViewModel.File);

                    if (!string.IsNullOrWhiteSpace(fileUploadViewModel.FileName))
                    {
                        _culturalExchangeFileUploadAppService.Add(fileUploadViewModel);
                        return Json(Ok());
                    }
                }

                return Json(Conflict());
            }
            catch (Exception ex)
            {
                _fileUploadAppService.Delete(_appSetttings.Value.UploadFilePath, fileUploadViewModel.FileName);

                return Json(BadRequest());
            }
        }

    }
}

INTER.CORE/Inter.Core.Presentation/Controllers/PaymentCulturalExchangeController.cs
using Inter.Core.App.Intefaces;
using Inter.Core.App.Intefaces.Identity;
using Inter.Core.App.ViewModel;
using Inter.Core.Presentation.Configuration;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Inter.Core.Presentation.Controllers
{
    [Authorize(Roles = "Admin, Manager, PaymentCulturalExchange")]
    public class PaymentCulturalExchangeController : Controller
    {
        private readonly IOptions<AppSettings> _appSetttings;
        private readonly IFileUploadAppService _fileUploadAppService;
        private readonly IApplicationUserAppService _applicationUserAppService;
        private readonly IPaymentCulturalExchangeAppService _paymentCulturalExchangeAppService;
        private readonly ICulturalExchangeAppService _culturalExchangeAppService;

        public PaymentCulturalExchangeController(
            IOptions<AppSettings> appSetttings,
            IFileUploadAppService fileUploadAppService,
            ICulturalExchangeAppService culturalExchangeAppService,
            IApplicationUserAppService applicationUserAppService,
            IPaymentCulturalExchangeAppService paymentCulturalExchangeAppService)
        {
            _appSetttings = appSetttings;
            _fileUploadAppService = fileUploadAppService;
            _culturalExchangeAppService = culturalExchangeAppService;
            _applicationUserAppService = applicationUserAppService;
            _paymentCulturalExchangeAppService = paymentCulturalExchangeAppService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _applicationUserAppService.GetById(userId);

            if (user == null)
                return NotFound();

            var paymentsList = _paymentCulturalExchangeAppService.GetAll(user.EnvironmentId);

            return View(paymentsList);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var payment = _paymentCulturalExchangeAppService.GetById(id);

            return View(payment);
        }

        public async Task<IActionResult> Create()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _applicationUserAppService.GetById(userId);

            if (user == null)
                return NotFound();

            ViewBag.EnvironmentId = user.EnvironmentId;
            ViewBag.CulturalExchange = _culturalExchangeAppService.GetAllPaymentFinished(user.EnvironmentId);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PaymentCulturalExchangeViewModel paymentCulturalExchangeViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var culturalExchange = _culturalExchangeAppService.GetById(paymentCulturalExchangeViewModel.CulturalExchangeId);

                    paymentCulturalExchangeViewModel.FileName = await _fileUploadAppService.Upload(
                        _appSetttings.Value.UploadFilePath + culturalExchange.Id, null, paymentCulturalExchangeViewModel.File);

                    paymentCulturalExchangeViewModel = _paymentCulturalExchangeAppService.Add(paymentCulturalExchangeViewModel);

                    if (!paymentCulturalExchangeViewModel.ValidationResult.Any())
                        return RedirectToAction("Index", "ReceivePaymentCulturalExchange");
                }

                return Json(Conflict());
            }
            catch (Exception ex)
            {
                _fileUploadAppService.Delete(_appSetttings.Value.UploadFilePath, paymentCulturalExchangeViewModel.FileName);
                return Json(BadRequest());
            }
        }

        //private async Task<string> UploadFile(IFormFile file)
        //{
        //    if (file == null || file.Length == 0)
        //        return null;

        //    string fileName = Guid.NewGuid().ToString() + ".pdf";

        //    var pathFolder = _appSetttings.Value.UploadFilePath;

        //    var pathCombine = Path.Combine(
        //        pathFolder,
        //                fileName);

        //    if (!Directory.Exists(pathFolder))
        //        Directory.CreateDirectory(pathFolder);

        //    using (var stream = new FileStream(pathCombine, FileMode.Create))
        //    {
        //        await file.CopyToAsync(stream);
        //    }

        //    return fileName;
        //}

        //private void DeleteFile(string fileName)
        //{
        //    var path = Path.Combine(_appSetttings.Value.UploadFilePath,
        //               fileName);

        //    if (System.IO.File.Exists(path))
        //        System.IO.File.Delete(path);
        //}
    }
}

INTER.CORE/Inter.Core.Presentation/Views/PaymentCulturalExchange/Create.cshtml
@model PaymentCulturalExchangeViewModel

@using Inter.Core.App.Enumerables;

<div class="container">

    <h1 class="h3 mb-2 text-gray-800">Payment - NEW</h1>

    <table class="table table-striped">
        <tbody>
            <tr>
                <td colspan="1">
                    <form id="form-create-culturalExchange" asp-action="OnCreate" class="well form-horizontal" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row">
                            <div class="col-md-4">
                                <label class="col-md-6 control-label">Customer Id*</label>
                                <input name="customerId" id="customerId" class="form-control" type="text" value="" disabled>
                            </div>

                            <div class="col-md-4">
                                <label class="col-md-4 control-label">Full Name*</label>
                                <select asp-for="CulturalExchangeId" required class="form-control" id="dropDownCulturalExchange"
                                        asp-items="@(new SelectList(ViewBag.CulturalExchange,"Id","StudentViewModel.FullName"))">
                                    <option value="0">Please select one</option>
                                </select>
                                <span asp-validation-for="CulturalExchangeViewModel" class="text-danger"></span>
                            </div>
                        </div>

                        <br />

                        @await Html.PartialAsync("~/Views/PaymentCulturalExchange/_partial/_form_create_edit.cshtml", Model)

                        <input hidden asp-for="EnviromentId" value="@ViewBag.EnvironmentId" />

                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="form-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        </div>

                    </form>

                </td>
            </tr>
        </tbody>
    </table>
</div>


@section Scripts {

    <script src="~/js/Util/Util.js"></script>
    <script src="~/js/PaymentCulturalExchange/PaymentCulturalExchange.js"></script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

INTER.CORE/Inter.Core.Presentation/Views/PaymentCulturalExchange/Index.cshtml
@model IEnumerable<PaymentCulturalExchangeViewModel>

<div class="container-fluid">
    <!-- Page Heading -->
    @*<h1 class="h3 mb-2 text-gray-800">Receive Payment Cultural Exchange</h1>
        <p class="mb-4"><a target="_blank" href="ReceivePaymentCulturalExchange/Create">NEW</a></p>*@
    <!-- DataTales Example -->

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List</h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Cultomer Id</th>
                            <th>Full Name</th>
                            <th>Arrival Date</th>
                            <th>Start Date</th>
                            <th>Date of Payment</th>
                            <th>Status</th>
                            <th>Value</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="culturalExchangeTBody">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.CulturalExchangeViewModel.StudentViewModel.CustomerId
                                </td>
                                <td>
                                    @item.CulturalExchangeViewModel.StudentViewModel.FullName
                                </td>
                                <td>
                                    @item.CulturalExchangeViewModel.ArrivalDateTime
                                </td>
                                <td>
                                    @item.CulturalExchangeViewModel.StartDate
                                </td>
                                <td>
                                    @item.DateOfPayment
                                </td>
                                <td>
                                    @item.Status
                                </td>
                                <td>
                                    @item.Value
                                </td>
                              
                                <td>
                                    <a asp-action="Download" asp-controller="FileUpload" asp-route-fileName="@item.FileName" class="btn btn-link btn-circle btn-sm"><i class="fas fa-download"></i></a>

                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info btn-circle btn-sm"><i class="fas fa-edit"></i></a>

                                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-facebook btn-circle btn-sm"><i class="fas fa-info"></i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="~/js/demo/datatables.min.js"></script>